### POST Create new user
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "John Doe",
    "number": "485-485-4589"
}

### GET all
GET http://localhost:3001/api/persons 

### GET specific user by id 
GET http://localhost:3001/api/persons/3
